# Generated by Django 3.0.5 on 2020-04-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200417_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitems',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
